// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Author: Jumbo 
// source: GoodsInfo.proto

#ifndef PROTOBUF_GoodsInfo_2eproto__INCLUDED
#define PROTOBUF_GoodsInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace JX {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_GoodsInfo_2eproto();
void protobuf_AssignDesc_GoodsInfo_2eproto();
void protobuf_ShutdownFile_GoodsInfo_2eproto();

class GoodsInfo;
class GoodsInfo_ARRAY;
class GoodsInfo_GoodsAttr;
class GoodsInfo_Price;

// ===================================================================

class GoodsInfo_Price : public ::google::protobuf::Message {
 public:
  GoodsInfo_Price();
  virtual ~GoodsInfo_Price();

  GoodsInfo_Price(const GoodsInfo_Price& from);

  inline GoodsInfo_Price& operator=(const GoodsInfo_Price& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GoodsInfo_Price& default_instance();

  void Swap(GoodsInfo_Price* other);

  // implements Message ----------------------------------------------

  inline GoodsInfo_Price* New() const { return New(NULL); }

  GoodsInfo_Price* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GoodsInfo_Price& from);
  void MergeFrom(const GoodsInfo_Price& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GoodsInfo_Price* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 price_dq = 1;
  void clear_price_dq();
  static const int kPriceDqFieldNumber = 1;
  ::google::protobuf::uint32 price_dq() const;
  void set_price_dq(::google::protobuf::uint32 value);

  // optional uint32 price_gold = 2;
  void clear_price_gold();
  static const int kPriceGoldFieldNumber = 2;
  ::google::protobuf::uint32 price_gold() const;
  void set_price_gold(::google::protobuf::uint32 value);

  // optional uint32 price_value = 3;
  void clear_price_value();
  static const int kPriceValueFieldNumber = 3;
  ::google::protobuf::uint32 price_value() const;
  void set_price_value(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:JX.GoodsInfo.Price)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 price_dq_;
  ::google::protobuf::uint32 price_gold_;
  ::google::protobuf::uint32 price_value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_GoodsInfo_2eproto();
  friend void protobuf_AssignDesc_GoodsInfo_2eproto();
  friend void protobuf_ShutdownFile_GoodsInfo_2eproto();

  void InitAsDefaultInstance();
  static GoodsInfo_Price* default_instance_;
};
// -------------------------------------------------------------------

class GoodsInfo_GoodsAttr : public ::google::protobuf::Message {
 public:
  GoodsInfo_GoodsAttr();
  virtual ~GoodsInfo_GoodsAttr();

  GoodsInfo_GoodsAttr(const GoodsInfo_GoodsAttr& from);

  inline GoodsInfo_GoodsAttr& operator=(const GoodsInfo_GoodsAttr& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GoodsInfo_GoodsAttr& default_instance();

  void Swap(GoodsInfo_GoodsAttr* other);

  // implements Message ----------------------------------------------

  inline GoodsInfo_GoodsAttr* New() const { return New(NULL); }

  GoodsInfo_GoodsAttr* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GoodsInfo_GoodsAttr& from);
  void MergeFrom(const GoodsInfo_GoodsAttr& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GoodsInfo_GoodsAttr* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 attr_type = 1;
  void clear_attr_type();
  static const int kAttrTypeFieldNumber = 1;
  ::google::protobuf::uint32 attr_type() const;
  void set_attr_type(::google::protobuf::uint32 value);

  // optional uint32 attr_value = 2;
  void clear_attr_value();
  static const int kAttrValueFieldNumber = 2;
  ::google::protobuf::uint32 attr_value() const;
  void set_attr_value(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:JX.GoodsInfo.GoodsAttr)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 attr_type_;
  ::google::protobuf::uint32 attr_value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_GoodsInfo_2eproto();
  friend void protobuf_AssignDesc_GoodsInfo_2eproto();
  friend void protobuf_ShutdownFile_GoodsInfo_2eproto();

  void InitAsDefaultInstance();
  static GoodsInfo_GoodsAttr* default_instance_;
};
// -------------------------------------------------------------------

class GoodsInfo : public ::google::protobuf::Message {
 public:
  GoodsInfo();
  virtual ~GoodsInfo();

  GoodsInfo(const GoodsInfo& from);

  inline GoodsInfo& operator=(const GoodsInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GoodsInfo& default_instance();

  void Swap(GoodsInfo* other);

  // implements Message ----------------------------------------------

  inline GoodsInfo* New() const { return New(NULL); }

  GoodsInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GoodsInfo& from);
  void MergeFrom(const GoodsInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GoodsInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef GoodsInfo_Price Price;
  typedef GoodsInfo_GoodsAttr GoodsAttr;

  // accessors -------------------------------------------------------

  // optional uint32 goods_id = 1;
  void clear_goods_id();
  static const int kGoodsIdFieldNumber = 1;
  ::google::protobuf::uint32 goods_id() const;
  void set_goods_id(::google::protobuf::uint32 value);

  // optional bytes name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const void* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional uint32 sex = 3;
  void clear_sex();
  static const int kSexFieldNumber = 3;
  ::google::protobuf::uint32 sex() const;
  void set_sex(::google::protobuf::uint32 value);

  // optional uint32 level_limit = 4;
  void clear_level_limit();
  static const int kLevelLimitFieldNumber = 4;
  ::google::protobuf::uint32 level_limit() const;
  void set_level_limit(::google::protobuf::uint32 value);

  // optional int32 club_vip_level = 5;
  void clear_club_vip_level();
  static const int kClubVipLevelFieldNumber = 5;
  ::google::protobuf::int32 club_vip_level() const;
  void set_club_vip_level(::google::protobuf::int32 value);

  // optional int32 qb_2 = 6;
  void clear_qb_2();
  static const int kQb2FieldNumber = 6;
  ::google::protobuf::int32 qb_2() const;
  void set_qb_2(::google::protobuf::int32 value);

  // optional uint32 consume_type = 7;
  void clear_consume_type();
  static const int kConsumeTypeFieldNumber = 7;
  ::google::protobuf::uint32 consume_type() const;
  void set_consume_type(::google::protobuf::uint32 value);

  // optional uint32 time_unit = 8;
  void clear_time_unit();
  static const int kTimeUnitFieldNumber = 8;
  ::google::protobuf::uint32 time_unit() const;
  void set_time_unit(::google::protobuf::uint32 value);

  // optional uint32 is_online = 9;
  void clear_is_online();
  static const int kIsOnlineFieldNumber = 9;
  ::google::protobuf::uint32 is_online() const;
  void set_is_online(::google::protobuf::uint32 value);

  // optional uint32 can_buy = 10;
  void clear_can_buy();
  static const int kCanBuyFieldNumber = 10;
  ::google::protobuf::uint32 can_buy() const;
  void set_can_buy(::google::protobuf::uint32 value);

  // optional uint32 can_recharge = 11;
  void clear_can_recharge();
  static const int kCanRechargeFieldNumber = 11;
  ::google::protobuf::uint32 can_recharge() const;
  void set_can_recharge(::google::protobuf::uint32 value);

  // optional bytes online_time = 12;
  void clear_online_time();
  static const int kOnlineTimeFieldNumber = 12;
  const ::std::string& online_time() const;
  void set_online_time(const ::std::string& value);
  void set_online_time(const char* value);
  void set_online_time(const void* value, size_t size);
  ::std::string* mutable_online_time();
  ::std::string* release_online_time();
  void set_allocated_online_time(::std::string* online_time);

  // optional bytes offline_time = 13;
  void clear_offline_time();
  static const int kOfflineTimeFieldNumber = 13;
  const ::std::string& offline_time() const;
  void set_offline_time(const ::std::string& value);
  void set_offline_time(const char* value);
  void set_offline_time(const void* value, size_t size);
  ::std::string* mutable_offline_time();
  ::std::string* release_offline_time();
  void set_allocated_offline_time(::std::string* offline_time);

  // repeated uint32 privileged_plat_id_list = 14;
  int privileged_plat_id_list_size() const;
  void clear_privileged_plat_id_list();
  static const int kPrivilegedPlatIdListFieldNumber = 14;
  ::google::protobuf::uint32 privileged_plat_id_list(int index) const;
  void set_privileged_plat_id_list(int index, ::google::protobuf::uint32 value);
  void add_privileged_plat_id_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      privileged_plat_id_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_privileged_plat_id_list();

  // optional uint32 privileged_plat_is_online = 15;
  void clear_privileged_plat_is_online();
  static const int kPrivilegedPlatIsOnlineFieldNumber = 15;
  ::google::protobuf::uint32 privileged_plat_is_online() const;
  void set_privileged_plat_is_online(::google::protobuf::uint32 value);

  // optional uint32 privileged_plat_can_buy = 16;
  void clear_privileged_plat_can_buy();
  static const int kPrivilegedPlatCanBuyFieldNumber = 16;
  ::google::protobuf::uint32 privileged_plat_can_buy() const;
  void set_privileged_plat_can_buy(::google::protobuf::uint32 value);

  // optional uint32 privileged_plat_can_recharge = 17;
  void clear_privileged_plat_can_recharge();
  static const int kPrivilegedPlatCanRechargeFieldNumber = 17;
  ::google::protobuf::uint32 privileged_plat_can_recharge() const;
  void set_privileged_plat_can_recharge(::google::protobuf::uint32 value);

  // optional uint32 payment_terms = 18;
  void clear_payment_terms();
  static const int kPaymentTermsFieldNumber = 18;
  ::google::protobuf::uint32 payment_terms() const;
  void set_payment_terms(::google::protobuf::uint32 value);

  // optional bytes valid_time = 19;
  void clear_valid_time();
  static const int kValidTimeFieldNumber = 19;
  const ::std::string& valid_time() const;
  void set_valid_time(const ::std::string& value);
  void set_valid_time(const char* value);
  void set_valid_time(const void* value, size_t size);
  ::std::string* mutable_valid_time();
  ::std::string* release_valid_time();
  void set_allocated_valid_time(::std::string* valid_time);

  // optional uint32 sort_priority = 20;
  void clear_sort_priority();
  static const int kSortPriorityFieldNumber = 20;
  ::google::protobuf::uint32 sort_priority() const;
  void set_sort_priority(::google::protobuf::uint32 value);

  // optional int32 suit_number = 21;
  void clear_suit_number();
  static const int kSuitNumberFieldNumber = 21;
  ::google::protobuf::int32 suit_number() const;
  void set_suit_number(::google::protobuf::int32 value);

  // optional uint32 bag_sort_priority = 22;
  void clear_bag_sort_priority();
  static const int kBagSortPriorityFieldNumber = 22;
  ::google::protobuf::uint32 bag_sort_priority() const;
  void set_bag_sort_priority(::google::protobuf::uint32 value);

  // optional bytes status = 23;
  void clear_status();
  static const int kStatusFieldNumber = 23;
  const ::std::string& status() const;
  void set_status(const ::std::string& value);
  void set_status(const char* value);
  void set_status(const void* value, size_t size);
  ::std::string* mutable_status();
  ::std::string* release_status();
  void set_allocated_status(::std::string* status);

  // optional uint32 rank = 24;
  void clear_rank();
  static const int kRankFieldNumber = 24;
  ::google::protobuf::uint32 rank() const;
  void set_rank(::google::protobuf::uint32 value);

  // optional uint32 price_discount = 25;
  void clear_price_discount();
  static const int kPriceDiscountFieldNumber = 25;
  ::google::protobuf::uint32 price_discount() const;
  void set_price_discount(::google::protobuf::uint32 value);

  // optional uint32 vip_discount = 26;
  void clear_vip_discount();
  static const int kVipDiscountFieldNumber = 26;
  ::google::protobuf::uint32 vip_discount() const;
  void set_vip_discount(::google::protobuf::uint32 value);

  // repeated .JX.GoodsInfo.Price price_table = 27;
  int price_table_size() const;
  void clear_price_table();
  static const int kPriceTableFieldNumber = 27;
  const ::JX::GoodsInfo_Price& price_table(int index) const;
  ::JX::GoodsInfo_Price* mutable_price_table(int index);
  ::JX::GoodsInfo_Price* add_price_table();
  ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo_Price >*
      mutable_price_table();
  const ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo_Price >&
      price_table() const;

  // repeated .JX.GoodsInfo.GoodsAttr goods_attr = 28;
  int goods_attr_size() const;
  void clear_goods_attr();
  static const int kGoodsAttrFieldNumber = 28;
  const ::JX::GoodsInfo_GoodsAttr& goods_attr(int index) const;
  ::JX::GoodsInfo_GoodsAttr* mutable_goods_attr(int index);
  ::JX::GoodsInfo_GoodsAttr* add_goods_attr();
  ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo_GoodsAttr >*
      mutable_goods_attr();
  const ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo_GoodsAttr >&
      goods_attr() const;

  // optional bytes description = 29;
  void clear_description();
  static const int kDescriptionFieldNumber = 29;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  void set_description(const char* value);
  void set_description(const void* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // optional uint32 limit_id = 30;
  void clear_limit_id();
  static const int kLimitIdFieldNumber = 30;
  ::google::protobuf::uint32 limit_id() const;
  void set_limit_id(::google::protobuf::uint32 value);

  // optional bytes subSystemId = 31;
  void clear_subsystemid();
  static const int kSubSystemIdFieldNumber = 31;
  const ::std::string& subsystemid() const;
  void set_subsystemid(const ::std::string& value);
  void set_subsystemid(const char* value);
  void set_subsystemid(const void* value, size_t size);
  ::std::string* mutable_subsystemid();
  ::std::string* release_subsystemid();
  void set_allocated_subsystemid(::std::string* subsystemid);

  // @@protoc_insertion_point(class_scope:JX.GoodsInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 goods_id_;
  ::google::protobuf::uint32 sex_;
  ::google::protobuf::uint32 level_limit_;
  ::google::protobuf::int32 club_vip_level_;
  ::google::protobuf::int32 qb_2_;
  ::google::protobuf::uint32 consume_type_;
  ::google::protobuf::uint32 time_unit_;
  ::google::protobuf::uint32 is_online_;
  ::google::protobuf::uint32 can_buy_;
  ::google::protobuf::uint32 can_recharge_;
  ::google::protobuf::internal::ArenaStringPtr online_time_;
  ::google::protobuf::internal::ArenaStringPtr offline_time_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > privileged_plat_id_list_;
  mutable int _privileged_plat_id_list_cached_byte_size_;
  ::google::protobuf::uint32 privileged_plat_is_online_;
  ::google::protobuf::uint32 privileged_plat_can_buy_;
  ::google::protobuf::uint32 privileged_plat_can_recharge_;
  ::google::protobuf::uint32 payment_terms_;
  ::google::protobuf::internal::ArenaStringPtr valid_time_;
  ::google::protobuf::uint32 sort_priority_;
  ::google::protobuf::int32 suit_number_;
  ::google::protobuf::internal::ArenaStringPtr status_;
  ::google::protobuf::uint32 bag_sort_priority_;
  ::google::protobuf::uint32 rank_;
  ::google::protobuf::uint32 price_discount_;
  ::google::protobuf::uint32 vip_discount_;
  ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo_Price > price_table_;
  ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo_GoodsAttr > goods_attr_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::internal::ArenaStringPtr subsystemid_;
  ::google::protobuf::uint32 limit_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_GoodsInfo_2eproto();
  friend void protobuf_AssignDesc_GoodsInfo_2eproto();
  friend void protobuf_ShutdownFile_GoodsInfo_2eproto();

  void InitAsDefaultInstance();
  static GoodsInfo* default_instance_;
};
// -------------------------------------------------------------------

class GoodsInfo_ARRAY : public ::google::protobuf::Message {
 public:
  GoodsInfo_ARRAY();
  virtual ~GoodsInfo_ARRAY();

  GoodsInfo_ARRAY(const GoodsInfo_ARRAY& from);

  inline GoodsInfo_ARRAY& operator=(const GoodsInfo_ARRAY& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GoodsInfo_ARRAY& default_instance();

  void Swap(GoodsInfo_ARRAY* other);

  // implements Message ----------------------------------------------

  inline GoodsInfo_ARRAY* New() const { return New(NULL); }

  GoodsInfo_ARRAY* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GoodsInfo_ARRAY& from);
  void MergeFrom(const GoodsInfo_ARRAY& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GoodsInfo_ARRAY* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .JX.GoodsInfo items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::JX::GoodsInfo& items(int index) const;
  ::JX::GoodsInfo* mutable_items(int index);
  ::JX::GoodsInfo* add_items();
  ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo >&
      items() const;

  // @@protoc_insertion_point(class_scope:JX.GoodsInfo_ARRAY)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo > items_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_GoodsInfo_2eproto();
  friend void protobuf_AssignDesc_GoodsInfo_2eproto();
  friend void protobuf_ShutdownFile_GoodsInfo_2eproto();

  void InitAsDefaultInstance();
  static GoodsInfo_ARRAY* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GoodsInfo_Price

// optional uint32 price_dq = 1;
inline void GoodsInfo_Price::clear_price_dq() {
  price_dq_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo_Price::price_dq() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.Price.price_dq)
  return price_dq_;
}
inline void GoodsInfo_Price::set_price_dq(::google::protobuf::uint32 value) {
  
  price_dq_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.Price.price_dq)
}

// optional uint32 price_gold = 2;
inline void GoodsInfo_Price::clear_price_gold() {
  price_gold_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo_Price::price_gold() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.Price.price_gold)
  return price_gold_;
}
inline void GoodsInfo_Price::set_price_gold(::google::protobuf::uint32 value) {
  
  price_gold_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.Price.price_gold)
}

// optional uint32 price_value = 3;
inline void GoodsInfo_Price::clear_price_value() {
  price_value_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo_Price::price_value() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.Price.price_value)
  return price_value_;
}
inline void GoodsInfo_Price::set_price_value(::google::protobuf::uint32 value) {
  
  price_value_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.Price.price_value)
}

// -------------------------------------------------------------------

// GoodsInfo_GoodsAttr

// optional uint32 attr_type = 1;
inline void GoodsInfo_GoodsAttr::clear_attr_type() {
  attr_type_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo_GoodsAttr::attr_type() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.GoodsAttr.attr_type)
  return attr_type_;
}
inline void GoodsInfo_GoodsAttr::set_attr_type(::google::protobuf::uint32 value) {
  
  attr_type_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.GoodsAttr.attr_type)
}

// optional uint32 attr_value = 2;
inline void GoodsInfo_GoodsAttr::clear_attr_value() {
  attr_value_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo_GoodsAttr::attr_value() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.GoodsAttr.attr_value)
  return attr_value_;
}
inline void GoodsInfo_GoodsAttr::set_attr_value(::google::protobuf::uint32 value) {
  
  attr_value_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.GoodsAttr.attr_value)
}

// -------------------------------------------------------------------

// GoodsInfo

// optional uint32 goods_id = 1;
inline void GoodsInfo::clear_goods_id() {
  goods_id_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::goods_id() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.goods_id)
  return goods_id_;
}
inline void GoodsInfo::set_goods_id(::google::protobuf::uint32 value) {
  
  goods_id_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.goods_id)
}

// optional bytes name = 2;
inline void GoodsInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::name() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.name)
}
inline void GoodsInfo::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JX.GoodsInfo.name)
}
inline void GoodsInfo::set_name(const void* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JX.GoodsInfo.name)
}
inline ::std::string* GoodsInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:JX.GoodsInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:JX.GoodsInfo.name)
}

// optional uint32 sex = 3;
inline void GoodsInfo::clear_sex() {
  sex_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::sex() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.sex)
  return sex_;
}
inline void GoodsInfo::set_sex(::google::protobuf::uint32 value) {
  
  sex_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.sex)
}

// optional uint32 level_limit = 4;
inline void GoodsInfo::clear_level_limit() {
  level_limit_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::level_limit() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.level_limit)
  return level_limit_;
}
inline void GoodsInfo::set_level_limit(::google::protobuf::uint32 value) {
  
  level_limit_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.level_limit)
}

// optional int32 club_vip_level = 5;
inline void GoodsInfo::clear_club_vip_level() {
  club_vip_level_ = 0;
}
inline ::google::protobuf::int32 GoodsInfo::club_vip_level() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.club_vip_level)
  return club_vip_level_;
}
inline void GoodsInfo::set_club_vip_level(::google::protobuf::int32 value) {
  
  club_vip_level_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.club_vip_level)
}

// optional int32 qb_2 = 6;
inline void GoodsInfo::clear_qb_2() {
  qb_2_ = 0;
}
inline ::google::protobuf::int32 GoodsInfo::qb_2() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.qb_2)
  return qb_2_;
}
inline void GoodsInfo::set_qb_2(::google::protobuf::int32 value) {
  
  qb_2_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.qb_2)
}

// optional uint32 consume_type = 7;
inline void GoodsInfo::clear_consume_type() {
  consume_type_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::consume_type() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.consume_type)
  return consume_type_;
}
inline void GoodsInfo::set_consume_type(::google::protobuf::uint32 value) {
  
  consume_type_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.consume_type)
}

// optional uint32 time_unit = 8;
inline void GoodsInfo::clear_time_unit() {
  time_unit_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::time_unit() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.time_unit)
  return time_unit_;
}
inline void GoodsInfo::set_time_unit(::google::protobuf::uint32 value) {
  
  time_unit_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.time_unit)
}

// optional uint32 is_online = 9;
inline void GoodsInfo::clear_is_online() {
  is_online_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::is_online() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.is_online)
  return is_online_;
}
inline void GoodsInfo::set_is_online(::google::protobuf::uint32 value) {
  
  is_online_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.is_online)
}

// optional uint32 can_buy = 10;
inline void GoodsInfo::clear_can_buy() {
  can_buy_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::can_buy() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.can_buy)
  return can_buy_;
}
inline void GoodsInfo::set_can_buy(::google::protobuf::uint32 value) {
  
  can_buy_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.can_buy)
}

// optional uint32 can_recharge = 11;
inline void GoodsInfo::clear_can_recharge() {
  can_recharge_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::can_recharge() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.can_recharge)
  return can_recharge_;
}
inline void GoodsInfo::set_can_recharge(::google::protobuf::uint32 value) {
  
  can_recharge_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.can_recharge)
}

// optional bytes online_time = 12;
inline void GoodsInfo::clear_online_time() {
  online_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::online_time() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.online_time)
  return online_time_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_online_time(const ::std::string& value) {
  
  online_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.online_time)
}
inline void GoodsInfo::set_online_time(const char* value) {
  
  online_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JX.GoodsInfo.online_time)
}
inline void GoodsInfo::set_online_time(const void* value, size_t size) {
  
  online_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JX.GoodsInfo.online_time)
}
inline ::std::string* GoodsInfo::mutable_online_time() {
  
  // @@protoc_insertion_point(field_mutable:JX.GoodsInfo.online_time)
  return online_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_online_time() {
  
  return online_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_online_time(::std::string* online_time) {
  if (online_time != NULL) {
    
  } else {
    
  }
  online_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), online_time);
  // @@protoc_insertion_point(field_set_allocated:JX.GoodsInfo.online_time)
}

// optional bytes offline_time = 13;
inline void GoodsInfo::clear_offline_time() {
  offline_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::offline_time() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.offline_time)
  return offline_time_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_offline_time(const ::std::string& value) {
  
  offline_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.offline_time)
}
inline void GoodsInfo::set_offline_time(const char* value) {
  
  offline_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JX.GoodsInfo.offline_time)
}
inline void GoodsInfo::set_offline_time(const void* value, size_t size) {
  
  offline_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JX.GoodsInfo.offline_time)
}
inline ::std::string* GoodsInfo::mutable_offline_time() {
  
  // @@protoc_insertion_point(field_mutable:JX.GoodsInfo.offline_time)
  return offline_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_offline_time() {
  
  return offline_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_offline_time(::std::string* offline_time) {
  if (offline_time != NULL) {
    
  } else {
    
  }
  offline_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), offline_time);
  // @@protoc_insertion_point(field_set_allocated:JX.GoodsInfo.offline_time)
}

// repeated uint32 privileged_plat_id_list = 14;
inline int GoodsInfo::privileged_plat_id_list_size() const {
  return privileged_plat_id_list_.size();
}
inline void GoodsInfo::clear_privileged_plat_id_list() {
  privileged_plat_id_list_.Clear();
}
inline ::google::protobuf::uint32 GoodsInfo::privileged_plat_id_list(int index) const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.privileged_plat_id_list)
  return privileged_plat_id_list_.Get(index);
}
inline void GoodsInfo::set_privileged_plat_id_list(int index, ::google::protobuf::uint32 value) {
  privileged_plat_id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.privileged_plat_id_list)
}
inline void GoodsInfo::add_privileged_plat_id_list(::google::protobuf::uint32 value) {
  privileged_plat_id_list_.Add(value);
  // @@protoc_insertion_point(field_add:JX.GoodsInfo.privileged_plat_id_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
GoodsInfo::privileged_plat_id_list() const {
  // @@protoc_insertion_point(field_list:JX.GoodsInfo.privileged_plat_id_list)
  return privileged_plat_id_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
GoodsInfo::mutable_privileged_plat_id_list() {
  // @@protoc_insertion_point(field_mutable_list:JX.GoodsInfo.privileged_plat_id_list)
  return &privileged_plat_id_list_;
}

// optional uint32 privileged_plat_is_online = 15;
inline void GoodsInfo::clear_privileged_plat_is_online() {
  privileged_plat_is_online_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::privileged_plat_is_online() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.privileged_plat_is_online)
  return privileged_plat_is_online_;
}
inline void GoodsInfo::set_privileged_plat_is_online(::google::protobuf::uint32 value) {
  
  privileged_plat_is_online_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.privileged_plat_is_online)
}

// optional uint32 privileged_plat_can_buy = 16;
inline void GoodsInfo::clear_privileged_plat_can_buy() {
  privileged_plat_can_buy_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::privileged_plat_can_buy() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.privileged_plat_can_buy)
  return privileged_plat_can_buy_;
}
inline void GoodsInfo::set_privileged_plat_can_buy(::google::protobuf::uint32 value) {
  
  privileged_plat_can_buy_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.privileged_plat_can_buy)
}

// optional uint32 privileged_plat_can_recharge = 17;
inline void GoodsInfo::clear_privileged_plat_can_recharge() {
  privileged_plat_can_recharge_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::privileged_plat_can_recharge() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.privileged_plat_can_recharge)
  return privileged_plat_can_recharge_;
}
inline void GoodsInfo::set_privileged_plat_can_recharge(::google::protobuf::uint32 value) {
  
  privileged_plat_can_recharge_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.privileged_plat_can_recharge)
}

// optional uint32 payment_terms = 18;
inline void GoodsInfo::clear_payment_terms() {
  payment_terms_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::payment_terms() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.payment_terms)
  return payment_terms_;
}
inline void GoodsInfo::set_payment_terms(::google::protobuf::uint32 value) {
  
  payment_terms_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.payment_terms)
}

// optional bytes valid_time = 19;
inline void GoodsInfo::clear_valid_time() {
  valid_time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::valid_time() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.valid_time)
  return valid_time_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_valid_time(const ::std::string& value) {
  
  valid_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.valid_time)
}
inline void GoodsInfo::set_valid_time(const char* value) {
  
  valid_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JX.GoodsInfo.valid_time)
}
inline void GoodsInfo::set_valid_time(const void* value, size_t size) {
  
  valid_time_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JX.GoodsInfo.valid_time)
}
inline ::std::string* GoodsInfo::mutable_valid_time() {
  
  // @@protoc_insertion_point(field_mutable:JX.GoodsInfo.valid_time)
  return valid_time_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_valid_time() {
  
  return valid_time_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_valid_time(::std::string* valid_time) {
  if (valid_time != NULL) {
    
  } else {
    
  }
  valid_time_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), valid_time);
  // @@protoc_insertion_point(field_set_allocated:JX.GoodsInfo.valid_time)
}

// optional uint32 sort_priority = 20;
inline void GoodsInfo::clear_sort_priority() {
  sort_priority_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::sort_priority() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.sort_priority)
  return sort_priority_;
}
inline void GoodsInfo::set_sort_priority(::google::protobuf::uint32 value) {
  
  sort_priority_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.sort_priority)
}

// optional int32 suit_number = 21;
inline void GoodsInfo::clear_suit_number() {
  suit_number_ = 0;
}
inline ::google::protobuf::int32 GoodsInfo::suit_number() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.suit_number)
  return suit_number_;
}
inline void GoodsInfo::set_suit_number(::google::protobuf::int32 value) {
  
  suit_number_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.suit_number)
}

// optional uint32 bag_sort_priority = 22;
inline void GoodsInfo::clear_bag_sort_priority() {
  bag_sort_priority_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::bag_sort_priority() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.bag_sort_priority)
  return bag_sort_priority_;
}
inline void GoodsInfo::set_bag_sort_priority(::google::protobuf::uint32 value) {
  
  bag_sort_priority_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.bag_sort_priority)
}

// optional bytes status = 23;
inline void GoodsInfo::clear_status() {
  status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::status() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.status)
  return status_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_status(const ::std::string& value) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.status)
}
inline void GoodsInfo::set_status(const char* value) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JX.GoodsInfo.status)
}
inline void GoodsInfo::set_status(const void* value, size_t size) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JX.GoodsInfo.status)
}
inline ::std::string* GoodsInfo::mutable_status() {
  
  // @@protoc_insertion_point(field_mutable:JX.GoodsInfo.status)
  return status_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_status() {
  
  return status_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_status(::std::string* status) {
  if (status != NULL) {
    
  } else {
    
  }
  status_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), status);
  // @@protoc_insertion_point(field_set_allocated:JX.GoodsInfo.status)
}

// optional uint32 rank = 24;
inline void GoodsInfo::clear_rank() {
  rank_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::rank() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.rank)
  return rank_;
}
inline void GoodsInfo::set_rank(::google::protobuf::uint32 value) {
  
  rank_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.rank)
}

// optional uint32 price_discount = 25;
inline void GoodsInfo::clear_price_discount() {
  price_discount_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::price_discount() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.price_discount)
  return price_discount_;
}
inline void GoodsInfo::set_price_discount(::google::protobuf::uint32 value) {
  
  price_discount_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.price_discount)
}

// optional uint32 vip_discount = 26;
inline void GoodsInfo::clear_vip_discount() {
  vip_discount_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::vip_discount() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.vip_discount)
  return vip_discount_;
}
inline void GoodsInfo::set_vip_discount(::google::protobuf::uint32 value) {
  
  vip_discount_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.vip_discount)
}

// repeated .JX.GoodsInfo.Price price_table = 27;
inline int GoodsInfo::price_table_size() const {
  return price_table_.size();
}
inline void GoodsInfo::clear_price_table() {
  price_table_.Clear();
}
inline const ::JX::GoodsInfo_Price& GoodsInfo::price_table(int index) const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.price_table)
  return price_table_.Get(index);
}
inline ::JX::GoodsInfo_Price* GoodsInfo::mutable_price_table(int index) {
  // @@protoc_insertion_point(field_mutable:JX.GoodsInfo.price_table)
  return price_table_.Mutable(index);
}
inline ::JX::GoodsInfo_Price* GoodsInfo::add_price_table() {
  // @@protoc_insertion_point(field_add:JX.GoodsInfo.price_table)
  return price_table_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo_Price >*
GoodsInfo::mutable_price_table() {
  // @@protoc_insertion_point(field_mutable_list:JX.GoodsInfo.price_table)
  return &price_table_;
}
inline const ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo_Price >&
GoodsInfo::price_table() const {
  // @@protoc_insertion_point(field_list:JX.GoodsInfo.price_table)
  return price_table_;
}

// repeated .JX.GoodsInfo.GoodsAttr goods_attr = 28;
inline int GoodsInfo::goods_attr_size() const {
  return goods_attr_.size();
}
inline void GoodsInfo::clear_goods_attr() {
  goods_attr_.Clear();
}
inline const ::JX::GoodsInfo_GoodsAttr& GoodsInfo::goods_attr(int index) const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.goods_attr)
  return goods_attr_.Get(index);
}
inline ::JX::GoodsInfo_GoodsAttr* GoodsInfo::mutable_goods_attr(int index) {
  // @@protoc_insertion_point(field_mutable:JX.GoodsInfo.goods_attr)
  return goods_attr_.Mutable(index);
}
inline ::JX::GoodsInfo_GoodsAttr* GoodsInfo::add_goods_attr() {
  // @@protoc_insertion_point(field_add:JX.GoodsInfo.goods_attr)
  return goods_attr_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo_GoodsAttr >*
GoodsInfo::mutable_goods_attr() {
  // @@protoc_insertion_point(field_mutable_list:JX.GoodsInfo.goods_attr)
  return &goods_attr_;
}
inline const ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo_GoodsAttr >&
GoodsInfo::goods_attr() const {
  // @@protoc_insertion_point(field_list:JX.GoodsInfo.goods_attr)
  return goods_attr_;
}

// optional bytes description = 29;
inline void GoodsInfo::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::description() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.description)
  return description_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.description)
}
inline void GoodsInfo::set_description(const char* value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JX.GoodsInfo.description)
}
inline void GoodsInfo::set_description(const void* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JX.GoodsInfo.description)
}
inline ::std::string* GoodsInfo::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:JX.GoodsInfo.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_description() {
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:JX.GoodsInfo.description)
}

// optional uint32 limit_id = 30;
inline void GoodsInfo::clear_limit_id() {
  limit_id_ = 0u;
}
inline ::google::protobuf::uint32 GoodsInfo::limit_id() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.limit_id)
  return limit_id_;
}
inline void GoodsInfo::set_limit_id(::google::protobuf::uint32 value) {
  
  limit_id_ = value;
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.limit_id)
}

// optional bytes subSystemId = 31;
inline void GoodsInfo::clear_subsystemid() {
  subsystemid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GoodsInfo::subsystemid() const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo.subSystemId)
  return subsystemid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_subsystemid(const ::std::string& value) {
  
  subsystemid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JX.GoodsInfo.subSystemId)
}
inline void GoodsInfo::set_subsystemid(const char* value) {
  
  subsystemid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JX.GoodsInfo.subSystemId)
}
inline void GoodsInfo::set_subsystemid(const void* value, size_t size) {
  
  subsystemid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JX.GoodsInfo.subSystemId)
}
inline ::std::string* GoodsInfo::mutable_subsystemid() {
  
  // @@protoc_insertion_point(field_mutable:JX.GoodsInfo.subSystemId)
  return subsystemid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GoodsInfo::release_subsystemid() {
  
  return subsystemid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GoodsInfo::set_allocated_subsystemid(::std::string* subsystemid) {
  if (subsystemid != NULL) {
    
  } else {
    
  }
  subsystemid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), subsystemid);
  // @@protoc_insertion_point(field_set_allocated:JX.GoodsInfo.subSystemId)
}

// -------------------------------------------------------------------

// GoodsInfo_ARRAY

// repeated .JX.GoodsInfo items = 1;
inline int GoodsInfo_ARRAY::items_size() const {
  return items_.size();
}
inline void GoodsInfo_ARRAY::clear_items() {
  items_.Clear();
}
inline const ::JX::GoodsInfo& GoodsInfo_ARRAY::items(int index) const {
  // @@protoc_insertion_point(field_get:JX.GoodsInfo_ARRAY.items)
  return items_.Get(index);
}
inline ::JX::GoodsInfo* GoodsInfo_ARRAY::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:JX.GoodsInfo_ARRAY.items)
  return items_.Mutable(index);
}
inline ::JX::GoodsInfo* GoodsInfo_ARRAY::add_items() {
  // @@protoc_insertion_point(field_add:JX.GoodsInfo_ARRAY.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo >*
GoodsInfo_ARRAY::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:JX.GoodsInfo_ARRAY.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::JX::GoodsInfo >&
GoodsInfo_ARRAY::items() const {
  // @@protoc_insertion_point(field_list:JX.GoodsInfo_ARRAY.items)
  return items_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace JX

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GoodsInfo_2eproto__INCLUDED
