# Generated by the protocol buffer compiler.  DO NOT EDIT!
#Author: Jumbo 
# source: AccountInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AccountInfo.proto',
  package='JX',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x41\x63\x63ountInfo.proto\x12\x02JX\"\x1b\n\x0b\x41\x63\x63ountInfo\x12\x0c\n\x04name\x18\x01 \x01(\x0c\"3\n\x11\x41\x63\x63ountInfo_ARRAY\x12\x1e\n\x05items\x18\x01 \x03(\x0b\x32\x0f.JX.AccountInfob\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACCOUNTINFO = _descriptor.Descriptor(
  name='AccountInfo',
  full_name='JX.AccountInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='JX.AccountInfo.name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=52,
)


_ACCOUNTINFO_ARRAY = _descriptor.Descriptor(
  name='AccountInfo_ARRAY',
  full_name='JX.AccountInfo_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='JX.AccountInfo_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=105,
)

_ACCOUNTINFO_ARRAY.fields_by_name['items'].message_type = _ACCOUNTINFO
DESCRIPTOR.message_types_by_name['AccountInfo'] = _ACCOUNTINFO
DESCRIPTOR.message_types_by_name['AccountInfo_ARRAY'] = _ACCOUNTINFO_ARRAY

AccountInfo = _reflection.GeneratedProtocolMessageType('AccountInfo', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTINFO,
  __module__ = 'AccountInfo_pb2'
  # @@protoc_insertion_point(class_scope:JX.AccountInfo)
  ))
_sym_db.RegisterMessage(AccountInfo)

AccountInfo_ARRAY = _reflection.GeneratedProtocolMessageType('AccountInfo_ARRAY', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTINFO_ARRAY,
  __module__ = 'AccountInfo_pb2'
  # @@protoc_insertion_point(class_scope:JX.AccountInfo_ARRAY)
  ))
_sym_db.RegisterMessage(AccountInfo_ARRAY)


# @@protoc_insertion_point(module_scope)
